name: bbb-session-insights

services:
  bsi:
    container_name: bsi
    env_file: .env
    build:
      context: .
    ports:
      - 3333:3000
    volumes:
      - /var/bigbluebutton/learning-dashboard/:/data
      - /var/bigbluebutton/published/presentation:/replays
